# Generated by Django 5.0.6 on 2024-07-19 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_items_item_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item_image_url',
            new_name='item_image',
        ),
    ]
